Added oh My zsh
jgamblin/MacOS-Config pull request #1
Opened 2017-11-15 08:04 UTC by Mehran

add oh my zsh

2017-11-15 08:49 UTC, Mehran reviewed
add theme and Plugins

2017-11-15 11:45 UTC, jgamblin commented
I dont personally use ZSH so I am not going to merge this as this is what I use to setup my macs.  I would love if you would Fork this and make it your own.

2018-03-12 10:52 UTC, jgamblin requested changes
That GIST point to your local profile so would only work for your system.

2018-09-14 02:06 UTC, aurj0917 commented
what a nice day if i am freedom!

2026-03-27 16:54 UTC, jgamblin commented
Hi\! Thank you for this contribution. I'm doing some housekeeping on my GitHub repos and closing PRs that have been open for more than 6 months. This one has been open for quite a while and I don't want to leave it hanging. If the changes are still relevant, please feel free to reopen or submit a fresh PR. Thanks again\!

2026-03-27 16:54 UTC, closed without merging